version: '3'
services:
  postgres:
    container_name: netchillPostgres
    image: postgres:latest
    environment:
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - ./data/:/var/lib/postgresql/data